name: Odoo CI/CD Docker Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # -------------------------------------------------------------
  # STAGE 1 : CI (Build Docker + Tests Unitaires Odoo)
  # -------------------------------------------------------------
  build-and-test:
    name: Build Docker & Run Odoo Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker Odoo
        run: |
          docker build -t odoo-parc-app:latest .

      - name: Exécution des tests unitaires dans le conteneur Docker
        run: |

            docker run --network container:postgres \
            -e HOST=127.0.0.1 \
            -e USER=admin \
            -e PASSWORD=odoo \
            odoo-parc-app:latest \
            odoo -i parc_automobile --test-enable --stop-after-init --log-level=test

  # -------------------------------------------------------------
  # STAGE 2 : CD (Continuous Deployment - Déploiement)
  # -------------------------------------------------------------
  deploy:
    name: Deploy to Production Server
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Connexion SSH & Mise à jour du serveur de Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/odoo-deployment
            git pull origin main
            docker compose build
            docker compose up -d
            docker exec odoo_container odoo -u parc_automobile -d db_prod --stop-after-init
            docker restart odoo_container